const AppStyles = {
  colors: {
    primaryColor: '#B95FA1', // E56C44, 8b0065, B95FA1
    tealAccentColor: '#28666E',
    blueAccentColor: '#033F63',
    accentColor: '#87a190',
    secondAccentColor: '#4D7393',
    inactiveGreyColor: '#626262',
    lightGrey: '#7f8c8d',
    separator: '#bdc3c7',
    primaryWhite: '#EBD1E4',
    primaryDark: '#874676',
    white: 'white',
    black: 'black',
    mateBlack: '#333333',
    grey: 'grey',
    green: 'green',
    onlineGreen: '#2ecc71',
    lightWhite: '#f7f7f7',
    primaryTransparent: 'rgba(185, 95, 161, 0.2)',
    lightWhiteTransparent: 'rgba(240, 240, 240, 0.1)',
  },
  fonts: {
    FONT_BOLD: 'JosefinSans-Bold',
    FONT_THIN: 'JosefinSans-Thin',
    FONT_LIGHT: 'JosefinSans-Light',
    FONT_ITALIC: 'JosefinSans-Italic',
    FONT_REGULAR: 'JosefinSans-Regular',
    FONT_SEMIBOLD: 'JosefinSans-SemiBold',
    SECOND_FONT_BOLD: 'Lato-Bold',
    SECOND_FONT_THIN: 'Lato-Thin',
    SECOND_FONT_LIGHT: 'Lato-Light',
    SECOND_FONT_ITALIC: 'Lato-Italic',
    SECOND_FONT_REGULAR: 'Lato-Regular',
    SECOND_FONT_HAIRLINE: 'Lato-Hairline',
    SECOND_FONT_SEMIBOLD: 'Lato-SemiBold',
    OSWALD: 'Oswald-Bold',
    OSWALD_REGULAR: 'Oswald-Regular',
  },
};

export default AppStyles;
